### PR TITLE
Adds docker-compose with traefik support.

### LINKED ISSUE #207: [HELP] Configuration for own reverse proxy like NPM or traefik
Hello and thanks for this great project. Exactly what I was looking for for years!
But unfortunately I have some troubles with the setup. I am using my own reverse proxy (traefik and/or npm) and I am really confused with the setup and the different ports of the back- and frontends.

Finally with a lot of try and error I got an instance running showing me the webinterface behind my reverse proxy. Therefore I disabled the nginx container which would lead to a double proxy setup I think.
But then I got into the following troubles:

I try to login with the default (haven't changed any credentials in my testsetup yet) with user and pass "admin".
Within the docker logs, I then see this line:

```
web-1     | []
web-1     | { user: null }
```

Within the login mask, there is no reaction other than that line.
The same behavior when I try to register a user. Then I even don't see anything in the logfile.

During startup of the containers I don't get any errors but for me it looks like a missing connection between front- and backend.

Has anyone running AdventureLog behind a reverse proxy or can anyone tell me, what's going on with the login issue?

Thanks :)

### PR DESCRIPTION
**Pull request by tedski**
Configures the stack (frontend, backend, db, and static content) but adds a traefik reverse proxy instead of exposing the containers themselves.  The traefik proxy uses letsencrypt for certificate management.

fixes #207

### CODE REVIEW

**Review by stancubed — APPROVED** [review]
Just used an augmented version of this to test my setup behind NPM. Totally works and helps illustrate more the the traffic flow.

**Comment by seanmorley15** [comment]
Thanks for verifying!
I'm sure this will help many people :)

**Comment by pkirsche** [comment]
Thank you so much for this new option deploying behind traefik! Now I got it working right on the first try.

One little addition, I had to change the image name in the docker-compose-traefik.yaml:

From
```
  web:
    image: ghcr.io/seanmorley15/":latest
```
to
  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest

Otherwise I got an authentication error which I assume is caused by not existing image.
Am I right?

Please keep up the good work, I am so happy with this great project!

**Comment by seanmorley15** [comment]
Yes, you are totally right!
I just made those changes now.
I hope you enjoy!

**Comment by tedski** [comment]
Thanks for the quick fix, @seanmorley15.  Apologies for the errors.  Total brain fart when obfuscating things for the repo.

**Comment by seanmorley15** [comment]
No problem!!!
Thanks so much for adding the Traefik config, it will help many people!

**Comment by duggym122** [comment]
> Just used an augmented version of this to test my setup behind NPM. Totally works and helps illustrate more the the traffic flow.

@stancubed would you mind sharing that docker-compose? Not sure what I'm doing wrong, but my stack won't start until I remove the nginx container, leaving me without images, so I'd love to get some eyes on a working config using NPM.

**Comment by stancubed** [comment]
My NPM is managed via another stack so I have a shared network created and the frontend and nginx services are exposed to it. NPM can then reference them by their docker container names and the ports without needing to map an external port. 

In NPM, I've the frontend service set up as the host pointing to `http:adventurelog-web:3000` and I've added a custom location to the host so that /media points to `http:adventurelog-nginx:80`.

```yaml
version: "3.9"

services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-web
    environment:
      - PUBLIC_SERVER_URL=http://adventurelog-server:8000
      - BODY_SIZE_LIMIT=Infinity
    networks:
      - adventurelog
      - shared-network
    expose:
      - "3000"
    depends_on:
      - server

  db:
    image: postgres:latest
    container_name: adventurelog-db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: redacted
    networks:
      - adventurelog
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-server
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=redacted
      - SECRET_KEY=redacted
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@mydomain.com
      - PUBLIC_URL='https://adventurelog.mydomain.com'
      - CSRF_TRUSTED_ORIGINS=https://api.adventurelog.app,https://adventurelog.app,https://adventurelog.mydomain.com
      - DEBUG=False
      - FRONTEND_URL='https://adventurelog.mydomain.com'
    networks:
      - adventurelog
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - /home/user/config/appdata/adventurelog/config/media:/code/media

  nginx:
    image: nginx:latest
    container_name: adventurelog-nginx
    networks:
      - adventurelog
      - shared-network
    expose:
      - "80"
    volumes:
      - /home/user/config/appdata/adventurelog/config/media:/app/media
      - /home/user/config/appdata/adventurelog/config/nginx/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

networks:
  shared-network:
    name: shared-network
    external: true
  adventurelog:
    name: adventurelog
    
volumes:
  postgres_data:
```

**Pull request merged**
